//  Created by TagCommander on 04/02/2019.
//  Version : 4.3.1
//
//  Copyright (c) 2019 Commanders Act. All rights reserved.
//
// THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE BY HAND.

#ifndef __PRIVACY_GENERATED_H__
#define __PRIVACY_GENERATED_H__

#import <Foundation/Foundation.h>

extern NSString *const kTCPrivacyVersion;

extern NSString *const kTCReleaseDate;
extern NSString *const kTCReleaseTime;

#define TC_USE_IDFA

#endif //__PRIVACY_GENERATED_H__
