#!/bin/sh

TARGET_FOLDER="${BUILD_DIR}/${CONFIGURATION}-${PLATFORM_NAME}"

TOP_IOS_FOLDER="${PROJECT_DIR}/.."
PRI_TCDEMO_PROJECT_FOLDER="${TOP_IOS_FOLDER}/../../../Privacy-Demo/iOS/TCDemo/"

rm -Rf "${PRI_TCDEMO_PROJECT_FOLDER}/TCPrivacy.framework"
cp -R  "${TARGET_FOLDER}/TCPrivacy.framework" "${PRI_TCDEMO_PROJECT_FOLDER}"
