//  Created by TagCommander on 03/08/2020.
//  Version : 4.5.2
//
//  Copyright (c) 2020 Commanders Act. All rights reserved.
//
// THIS IS A GENERATED FILE. DO NOT EDIT THIS FILE BY HAND.

#ifndef __PARTNERS_GENERATED_H__
#define __PARTNERS_GENERATED_H__

#import <Foundation/Foundation.h>

extern NSString *const kTCPartnersVersion;

extern NSString *const kTCReleaseDate;
extern NSString *const kTCReleaseTime;

#define TC_USE_IDFA


#endif //__PARTNERS_GENERATED_H__
